import { existsSync } from 'node:fs'
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import yaml from 'yaml'
import {
  type NarwhalConfig,
  type McpServer,
  type ProviderProfile,
  CONFIG_VERSION,
  configSchema,
  defaultConfig,
} from '../shared/config-schema.js'

// ── Public API ─────────────────────────────────────────────────────────────

/** Result of a sync operation — what was written and where. */
export interface SyncResult {
  settingsYaml: string
  cordisPatchYaml: string
  providerCount: number
  mcpCount: number
  skillsEnabled: boolean
}

/**
 * Generate and write both DSH config files from a NarwhalConfig.
 * MUST be called BEFORE spawning the DSH process each startup.
 *
 * @param configPath  Narwhal's own config.json path (for header comment)
 * @param dshHome     DSH_HOME directory
 */
export async function syncDshConfig(
  config: NarwhalConfig,
  configPath: string,
  dshHome: string,
): Promise<SyncResult> {
  const settingsPath = join(dshHome, 'settings.yaml')
  const patchPath = join(dshHome, 'profiles', 'web', 'cordis.patch.yml')

  const settingsContent = buildSettingsYaml(config, configPath)
  const patchContent = buildCordisPatchYaml(config, configPath)

  await writeSettingsFile(settingsPath, settingsContent)
  await writePatchFile(patchPath, patchContent)

  return {
    settingsYaml: settingsPath,
    cordisPatchYaml: patchPath,
    providerCount: Object.keys(config.providers).length,
    mcpCount: config.mcpServers.length,
    skillsEnabled: config.skills.enabled,
  }
}

// ── Migration ──────────────────────────────────────────────────────────────

/**
 * On first run (no config.json yet, or old v1 format), read DSH's existing
 * settings.yaml and merge its content into a fresh NarwhalConfig.
 * The result is saved as config.json and becomes the authoritative source.
 */
export async function migrateFromDsh(
  configPath: string,
  dshHome: string,
): Promise<NarwhalConfig> {
  // 1. Start with defaults
  const merged: NarwhalConfig = { ...defaultConfig, providers: {}, mcpServers: [] }

  // 2. Merge existing config.json if it exists (pick up theme)
  if (existsSync(configPath)) {
    try {
      const raw = await readFile(configPath, 'utf-8')
      const parsed = JSON.parse(raw) as Record<string, unknown>
      if (typeof parsed.theme === 'string') merged.theme = parsed.theme as NarwhalConfig['theme']
    } catch {
      // ignore — fresh start
    }
  }

  // 3. Pull from DSH settings.yaml (the actual source of truth for runtime config)
  const dshSettingsPath = join(dshHome, 'settings.yaml')
  if (existsSync(dshSettingsPath)) {
    try {
      const raw = await readFile(dshSettingsPath, 'utf-8')
      const parsed = yaml.parse(raw) as Record<string, unknown> | null
      if (parsed && typeof parsed === 'object') {
        mergeDshProviders(merged, parsed['llm-pi-ai'])
        mergeDshDefaultModel(merged, parsed['agent-default-model'])
        mergeDshPermission(merged, parsed['permission'])
        mergeDshOnboarding(merged, parsed['ui-onboarding'])
      }
    } catch (error) {
      console.warn('[narwhal] migrateFromDsh: could not parse DSH settings.yaml:', error instanceof Error ? error.message : String(error))
    }
  }

  // 4. Write the migrated config.json
  const configDir = dirname(configPath)
  if (!existsSync(configDir)) await mkdir(configDir, { recursive: true })
  const validated = configSchema.parse(merged)
  await writeFile(configPath, JSON.stringify(validated, null, 2) + '\n', 'utf-8')

  console.log('[narwhal] migrateFromDsh: wrote config.json with', Object.keys(validated.providers).length, 'providers')
  return validated
}

// ── DSH settings.yaml builder ──────────────────────────────────────────────

const DSH_SETTINGS_HEADER = `# GENERATED BY NARWHAL — DO NOT EDIT MANUALLY
# Source: {configPath}
# Edit that file and restart Narwhal instead.

`

function buildSettingsYaml(config: NarwhalConfig, configPath: string): string {
  const doc: Record<string, unknown> = {}

  // ui-onboarding
  if (config.uiOnboarding) {
    doc['ui-onboarding'] = { welcomeNoticeVersion: config.uiOnboarding }
  }

  // llm-pi-ai.providers
  if (Object.keys(config.providers).length > 0) {
    doc['llm-pi-ai'] = {
      providers: config.providers,
    }
  }

  // agent-default-model
  if (config.defaultModel) {
    const sel: Record<string, unknown> = {
      provider: config.defaultModel.provider,
      model: config.defaultModel.model,
    }
    if (config.defaultModel.reasoningEffort) {
      sel.reasoningEffort = config.defaultModel.reasoningEffort
    }
    doc['agent-default-model'] = sel
  }

  // permission
  doc['permission'] = { defaultPreset: config.agent.permissionLevel }

  return DSH_SETTINGS_HEADER.replace('{configPath}', configPath) + yaml.stringify(doc)
}

// ── DSH cordis.patch.yml builder ───────────────────────────────────────────

const CORDIS_PATCH_HEADER = `# GENERATED BY NARWHAL — DO NOT EDIT MANUALLY
# Source: {configPath} (skills + mcpServers sections)
# Edit that file and restart Narwhal instead.

`

interface CordisEntry {
  id: string
  name?: string
  disabled?: boolean
  config?: Record<string, unknown>
}

function buildCordisPatchYaml(config: NarwhalConfig, configPath: string): string {
  const entries: CordisEntry[] = []

  // ── Skill system ────────────────────────────────────────────────────────
  if (config.skills.enabled) {
    entries.push(
      {
        id: 'skill-filesystem',
        disabled: false,
        config: {
          includeDefaultRoots: true,
          customSkillDirs: config.skills.customDirs,
          ...(config.skills.bundledDir ? { bundledSkillDir: config.skills.bundledDir } : {}),
        },
      },
      { id: 'tool-skill', disabled: false },
      { id: 'skill-badge', disabled: false },
    )
  }

  // ── MCP servers ────────────────────────────────────────────────────────
  for (const server of config.mcpServers) {
    entries.push(mcpServerToEntry(server))
  }

  return CORDIS_PATCH_HEADER.replace('{configPath}', configPath) + yaml.stringify(entries)
}

function mcpServerToEntry(server: McpServer): CordisEntry {
  const id = `mcp-${server.serverName}`
  const config: Record<string, unknown> = {
    transport: server.transport,
    serverName: server.serverName,
    toolCallTimeoutMs: server.toolCallTimeoutMs ?? 60000,
    failOnStartupError: server.failOnStartupError ?? false,
  }

  if (server.transport === 'stdio') {
    config.command = server.command
    config.args = server.args ?? []
    if (server.env) config.env = server.env
    if (server.cwd) config.cwd = server.cwd
  } else {
    config.url = server.url
    if (server.headers && Object.keys(server.headers).length > 0) config.headers = server.headers
  }

  return { id, name: '@deepseek-ai/dsh-mcp-client', config }
}

// ── File writers ───────────────────────────────────────────────────────────

async function writeSettingsFile(path: string, content: string): Promise<void> {
  const dir = dirname(path)
  if (!existsSync(dir)) await mkdir(dir, { recursive: true, mode: 0o700 })
  await writeFile(path, content, 'utf-8')
}

async function writePatchFile(path: string, content: string): Promise<void> {
  const dir = dirname(path)
  if (!existsSync(dir)) await mkdir(dir, { recursive: true })
  await writeFile(path, content, 'utf-8')
}

// ── DSH settings.yaml → config.json merge helpers ─────────────────────────

function mergeDshProviders(target: NarwhalConfig, section: unknown): void {
  if (!section || typeof section !== 'object') return
  const sectionObj = section as Record<string, unknown>
  const providersDict = sectionObj.providers
  if (!providersDict || typeof providersDict !== 'object') return

  for (const [name, profile] of Object.entries(providersDict as Record<string, unknown>)) {
    if (!profile || typeof profile !== 'object') continue
    target.providers[name] = profile as ProviderProfile
  }
}

function mergeDshDefaultModel(target: NarwhalConfig, section: unknown): void {
  if (!section || typeof section !== 'object') return
  const s = section as Record<string, unknown>
  const provider = typeof s.provider === 'string' ? s.provider : undefined
  const model = typeof s.model === 'string' ? s.model : undefined
  if (provider && model) {
    target.defaultModel = {
      provider,
      model,
      ...(typeof s.reasoningEffort === 'string' ? { reasoningEffort: s.reasoningEffort as 'low' | 'medium' | 'high' } : {}),
    }
  }
}

function mergeDshPermission(target: NarwhalConfig, section: unknown): void {
  if (!section || typeof section !== 'object') return
  const s = section as Record<string, unknown>
  const preset = s.defaultPreset
  if (typeof preset === 'string' && target.agent) {
    target.agent.permissionLevel = preset as NarwhalConfig['agent']['permissionLevel']
  }
}

function mergeDshOnboarding(target: NarwhalConfig, section: unknown): void {
  if (!section || typeof section !== 'object') return
  const s = section as Record<string, unknown>
  if (typeof s.welcomeNoticeVersion === 'string') {
    target.uiOnboarding = s.welcomeNoticeVersion
  }
}

// Re-export what callers need
export { CONFIG_VERSION }
