import { StrictMode, useEffect, useMemo, useRef, useState, type FormEvent, type KeyboardEvent as ReactKeyboardEvent, type ReactNode } from 'react'
import { createRoot } from 'react-dom/client'
import ReactMarkdown, { type Components } from 'react-markdown'
import rehypeHighlight from 'rehype-highlight'
import remarkGfm from 'remark-gfm'
import 'highlight.js/styles/github-dark.css'
import type { AgentConfiguration, AgentConversation, AgentSnapshot, ChatItem, DesktopSettings, Task, WorkbenchSnapshot } from '../shared/desktop-contract'
import { classifyActivity } from '../shared/activity-classifier'
import './styles.css'

// Detect Electron vs. browser (dev preview) environment and load the appropriate bridge
import './mock-bridge.js'
const _api = window.narwhal
if (!_api) throw new Error('Narwhal Forge desktop bridge is unavailable')
const api = _api
const blankConversation: AgentConversation = { sessions: [], messages: [], activity: [], running: false }
const blank: WorkbenchSnapshot = { workspaces: [], tasks: [], deliverables: [], panelOpen: false, git: { changes: [] }, conversation: blankConversation }
function Icon({ name }: { name: string }) { return <span className={`icon i-${name}`} aria-hidden="true" /> }
function statusText(state: AgentSnapshot['state']) { return state === 'ready' ? 'Agent ready' : state === 'starting' ? 'Starting agent' : 'Agent needs restart' }
function sessionTitle(item: AgentConversation['sessions'][number]) { return item.title === 'Untitled conversation' ? `Conversation · ${new Date(item.updatedAt).toLocaleDateString()}` : item.title }
const markdownComponents: Components = {
  code({ className, children, ...props }) {
    const language = /language-([\w-]+)/u.exec(className ?? '')?.[1]
    const text = String(children).replace(/\n$/u, '')
    if (!language) return <code className={className} {...props}>{children}</code>
    return <div className="code-block"><div><span>{language}</span><button type="button" aria-label="Copy code" onClick={() => void navigator.clipboard.writeText(text).catch(() => undefined)}>Copy</button></div><pre><code className={className} {...props}>{children}</code></pre></div>
  },
}
function MarkdownMessage({ content }: { content: string }) { return <ReactMarkdown remarkPlugins={[remarkGfm]} rehypePlugins={[rehypeHighlight]} components={markdownComponents}>{content}</ReactMarkdown> }

function App() {
  const [workbench, setWorkbench] = useState<WorkbenchSnapshot>(blank)
  const [conversation, setConversation] = useState<AgentConversation>(blankConversation)
  const [agent, setAgent] = useState<AgentSnapshot>({ state: 'starting' })
  const [settings, setSettings] = useState<DesktopSettings>({ appVersion: '0.1.0', runtimeVersion: 'Unavailable', dataDirectory: '' })
  const [configuration, setConfiguration] = useState<AgentConfiguration>({ available: false, writable: false, providers: [], models: [], permissionOptions: [], customProvider: { available: false, protocols: [] } })
  const [settingsOpen, setSettingsOpen] = useState(false)
  const [taskDraft, setTaskDraft] = useState(false)
  const [deliverableDraft, setDeliverableDraft] = useState(false)
  const [activityOpen, setActivityOpen] = useState(false)
  const [error, setError] = useState('')
  const selectedTask = useMemo(() => workbench.tasks.find((task) => task.id === workbench.selectedTaskId) ?? workbench.tasks[0], [workbench])
  const workspace = workbench.workspaces.find((item) => item.id === workbench.selectedWorkspaceId)
  const mutate = async (operation: () => Promise<WorkbenchSnapshot>) => { try { setError(''); const next = await operation(); setWorkbench(next); setConversation(next.conversation) } catch { setError('We couldn’t complete that action. Your local files were not changed.') } }
  const agentCall = async (operation: () => Promise<AgentConversation>) => { try { setError(''); setConversation(await operation()) } catch { setError('The local Agent could not complete that request. Check its status and try again.') } }
  useEffect(() => {
    void api.bootstrap().then(({ agent, workbench, settings }) => { setAgent(agent); setSettings(settings); setWorkbench(workbench); setConversation(workbench.conversation) }).catch(() => setError('Narwhal Forge could not load its local workspace data.'))
    const unAgent = api.onAgentState(setAgent); const unConversation = api.onConversation(setConversation)
    const unWorkbench = api.onWorkbench((next) => { setWorkbench(next); setConversation(next.conversation) })
    return () => { unAgent(); unConversation(); unWorkbench() }
  }, [])
  useEffect(() => { if (agent.state === 'ready') void api.getAgentConfiguration().then(setConfiguration).catch(() => undefined) }, [agent.state, conversation.selectedSessionId])
  const selectModel = async (input: { provider: string; model: string; reasoningEffort?: string }) => { try { setConfiguration(await api.selectAgentModel(input)) } catch { setError('The selected model could not be applied. Nothing was changed.') } }
  const selectPermission = async (preset: string) => { if (preset.toLowerCase().includes('full') && !window.confirm('Full access can allow unrestricted local tool operations. Continue?')) return; try { setConfiguration(await api.setDefaultPermission(preset)) } catch { setError('The selected permission could not be applied. Nothing was changed.') } }
  useEffect(() => { if (workspace && agent.state === 'ready') void agentCall(api.listSessions) }, [workspace?.id, agent.state])
  return <main className="app-shell">
    <header className="titlebar"><div className="drag-space"/><div className="brand no-drag"><img src="./assets/narwhal-icon.png"/><span>Narwhal Forge</span></div><div className="crumb no-drag">{workspace ? <><span>{workspace.name}</span><small>Personal workspace</small></> : <span>Choose a workspace</span>}</div><button className={`agent-status ${agent.state} no-drag`} onClick={() => agent.state !== 'ready' && void api.retryAgent()}><i/>{statusText(agent.state)}</button></header>
    <section className="layout">
      <aside className="sidebar">
        <button className="new-task" disabled={!workspace} onClick={() => setTaskDraft(true)}><Icon name="plus"/>New task</button>
        <SideBar workbench={workbench} conversation={conversation} workspace={workspace} agent={agent} selectedTask={selectedTask} choose={() => void mutate(api.chooseWorkspace)} selectWorkspace={(id) => void mutate(() => api.selectWorkspace(id))} createSession={() => void agentCall(api.createSession)} selectSession={(id) => void agentCall(() => api.selectSession(id))} selectTask={(id) => void mutate(() => api.selectTask(id))}/>
        <div className="side-foot"><button onClick={() => setSettingsOpen(true)}><Icon name="settings"/>Settings</button><span>Local only</span></div>
      </aside>
      <section className="agent-area">
        {error && <div className="notice"><span>{error}</span><button onClick={() => setError('')}>Dismiss</button></div>}
        {!workspace ? <EmptyWorkspace open={() => void mutate(api.chooseWorkspace)}/> : agent.state !== 'ready' ? <AgentLoading state={agent.state} retry={() => void api.retryAgent()}/> : !conversation.selectedSessionId ? <EmptyConversation create={() => void agentCall(api.createSession)}/> : <NativeConversation conversation={conversation} configuration={configuration} selectModel={selectModel} selectPermission={selectPermission} activityOpen={activityOpen} setActivityOpen={setActivityOpen} send={(text) => agentCall(() => api.sendPrompt(text))} cancel={() => void api.cancelPrompt().catch(() => setError('The Agent could not stop this turn.'))}/>} 
        <footer className="statusbar"><span><Icon name="branch"/>{workbench.git.branch ?? 'No Git repository'}</span><span><i className="local-dot"/>Local only</span><span className="runtime">{statusText(agent.state)}</span></footer>
      </section>
      {workbench.panelOpen && <button className="drawer-backdrop" aria-label="Close work context" onClick={() => void mutate(() => api.setPanelOpen(false))}/>} 
      <button className="panel-trigger" onClick={() => void mutate(() => api.setPanelOpen(!workbench.panelOpen))} aria-label="Toggle work context"><Icon name="panel"/></button>
      <aside className={workbench.panelOpen ? 'context-panel open' : 'context-panel'}><div className="panel-head"><div><p>Work context</p><h2>{selectedTask?.title ?? 'No task selected'}</h2></div><button title="Close panel" onClick={() => void mutate(() => api.setPanelOpen(false))}><Icon name="close"/></button></div>{!workspace ? <p className="panel-empty">Choose a workspace to keep its plan, changed files and deliverables together.</p> : <><TaskSection task={selectedTask} onSelect={(taskId) => void mutate(() => api.selectTask(taskId))} onNew={() => setTaskDraft(true)} onUpdate={(input) => void mutate(() => api.updateTask(input))} onTodo={(taskId, todoId, done) => void mutate(() => api.toggleTodo({ taskId, todoId, done }))} onAddTodo={(taskId, text) => void mutate(() => api.addTodo({ taskId, text }))}/><ChangesSection changes={workbench.git.changes}/><DeliverablesSection entries={workbench.deliverables} onNew={() => setDeliverableDraft(true)} onReveal={(path) => void api.revealDeliverable(path)} onRemove={(path) => void mutate(() => api.unpinDeliverable(path))}/></>}</aside>
    </section>
    {taskDraft && <TaskDialog close={() => setTaskDraft(false)} save={(title, goal) => mutate(() => api.createTask({ title, goal })).then(() => setTaskDraft(false))}/>} 
    {deliverableDraft && <DeliverableDialog close={() => setDeliverableDraft(false)} save={(relativePath, label) => mutate(() => api.pinDeliverable({ relativePath, label })).then(() => setDeliverableDraft(false))}/>} 
    {settingsOpen && <SettingsDialog settings={settings} agent={agent} close={() => setSettingsOpen(false)} restart={() => void api.retryAgent()}/>} 
  </main>
}

function SideBar({ workbench, conversation, workspace, agent, selectedTask, choose, selectWorkspace, createSession, selectSession, selectTask }: { workbench: WorkbenchSnapshot; conversation: AgentConversation; workspace: WorkbenchSnapshot['workspaces'][number] | undefined; agent: AgentSnapshot; selectedTask: Task | undefined; choose: () => void; selectWorkspace: (id: string) => void; createSession: () => void; selectSession: (id: string) => void; selectTask: (id: string) => void }) { return <><div className="side-section"><div className="section-heading"><span>Workspaces</span><button className="workspace-add" aria-label="Open workspace" title="Open workspace" onClick={choose}><Icon name="folder-plus"/></button></div><div className="workspace-list">{workbench.workspaces.length ? workbench.workspaces.map((item) => <button key={item.id} className={item.id === workbench.selectedWorkspaceId ? 'workspace active' : 'workspace'} onClick={() => selectWorkspace(item.id)}><Icon name="folder"/><span>{item.name}</span></button>) : <p className="empty-side">Open a local folder to begin.</p>}</div></div><div className="side-section"><div className="section-heading"><span>Conversations</span><button disabled={!workspace || agent.state !== 'ready'} title="New conversation" onClick={createSession}><Icon name="plus"/></button></div><div className="sessions">{workspace ? conversation.sessions.length ? conversation.sessions.map((item) => <button className={item.id === conversation.selectedSessionId ? 'session active' : 'session'} key={item.id} onClick={() => selectSession(item.id)}><span>{sessionTitle(item)}</span>{item.running && <i className="session-live"/>}</button>) : <p className="empty-side">Create a conversation to begin.</p> : <p className="empty-side">Choose a workspace first.</p>}</div></div><div className="side-section task-list"><div className="section-heading"><span>Tasks</span><span className="count">{workbench.tasks.length}</span></div>{workbench.tasks.slice(0, 4).map((task) => <button className={task.id === selectedTask?.id ? 'session active' : 'session'} key={task.id} onClick={() => selectTask(task.id)}><span>{task.title}</span><small>{task.status === 'done' ? 'Done' : 'Active'}</small></button>)}</div></> }
function NativeConversation({ conversation, configuration, selectModel, selectPermission, activityOpen, setActivityOpen, send, cancel }: { conversation: AgentConversation; configuration: AgentConfiguration; selectModel: (input: { provider: string; model: string; reasoningEffort?: string }) => Promise<void>; selectPermission: (preset: string) => Promise<void>; activityOpen: boolean; setActivityOpen: (value: boolean) => void; send: (text: string) => void; cancel: () => void }) { const phases = useMemo(() => activityPhases(conversation.activity), [conversation.activity]); const content = activityOpen ? phases.flatMap((phase) => phase.items) : conversation.messages; const timeline = useRef<HTMLDivElement>(null); const followOutput = useRef(true); useEffect(() => { if (conversation.running) followOutput.current = true; const element = timeline.current; if (element && followOutput.current) element.scrollTo({ top: element.scrollHeight, behavior: conversation.running ? 'auto' : 'smooth' }) }, [activityOpen, content, conversation.running]); const trackScroll = () => { const element = timeline.current; if (element) followOutput.current = element.scrollHeight - element.scrollTop - element.clientHeight < 48 }; return <div className="native-conversation"><div className="conversation-head"><div><p>Local Agent</p><h1>{activityOpen ? 'Activity' : 'Work'}</h1></div><div className="segmented"><button className={!activityOpen ? 'active' : ''} onClick={() => setActivityOpen(false)}>Work</button><button className={activityOpen ? 'active' : ''} onClick={() => setActivityOpen(true)}>Activity</button></div></div><div className={`timeline ${activityOpen ? 'activity-timeline' : ''}`} ref={timeline} onScroll={trackScroll}>{content.length ? activityOpen ? <div className="activity-phase-list">{phases.map((phase, index) => <section className="activity-phase" key={phase.id}><header><span>{index === phases.length - 1 && conversation.running ? 'Current turn' : `Turn ${index + 1}`}</span><strong>{phase.summary}</strong></header>{phase.items.map((item) => <TimelineItem key={item.id} item={item} activity/>)}</section>)}</div> : content.map((item) => <TimelineItem key={item.id} item={item} activity={false}/>) : <div className="conversation-empty"><img src="./assets/narwhal-icon.png"/><h2>{activityOpen ? 'Activity will appear here.' : 'Start with a clear task.'}</h2><p>{activityOpen ? 'Agent progress and meaningful tool work will stay quietly available here.' : 'Ask the local Agent to explore, build, fix or explain something in this workspace.'}</p></div>}</div><Composer running={conversation.running} configuration={configuration} hasSession={!!conversation.selectedSessionId} selectModel={selectModel} selectPermission={selectPermission} send={send} cancel={cancel}/></div> }
function normalizeActivity(item: ChatItem) {
  const descriptor = classifyActivity(
    item.kind === 'error' ? 'error' : 'activity',
    item.label,
    item.text,
    item.kind,
  )
  return {
    label: descriptor.label,
    text: descriptor.text,
    type: descriptor.type,
    hidden: descriptor.hidden,
  }
}
function activityPhases(items: readonly ChatItem[]) { const phases: Array<{ id: string; summary: string; items: ChatItem[] }> = []; for (const item of items) { const normalized = normalizeActivity(item); if (normalized.hidden) continue; const previous = phases[phases.length - 1]; const startsTurn = normalized.label === 'Turn started'; const duplicate = previous?.items.length && normalizeActivity(previous.items[previous.items.length - 1]).label === normalized.label && normalized.label !== 'Turn completed'; if (duplicate) continue; const phase = !previous || startsTurn ? { id: item.id, summary: normalized.label, items: [] as ChatItem[] } : previous; if (!previous || startsTurn) phases.push(phase); phase.items.push(item); phase.summary = normalized.label } return phases }
function TimelineItem({ item, activity }: { item: ChatItem; activity: boolean }) { if (activity || item.kind === 'activity' || item.kind === 'error') { const event = normalizeActivity(item); return <article className={`activity-row ${event.type}`}><span className="activity-mark"><Icon name={event.type}/></span><div><strong>{event.label}</strong><p>{event.text}</p></div></article> } return <article className={`message ${item.kind}`}><p className="message-label">{item.kind === 'user' ? 'You' : 'Narwhal Agent'}{item.streaming && <span className="streaming">Writing</span>}</p><div className="message-body"><MarkdownMessage content={item.text}/></div></article> }
function Composer({ running, configuration, hasSession, selectModel, selectPermission, send, cancel }: { running: boolean; configuration: AgentConfiguration; hasSession: boolean; selectModel: (input: { provider: string; model: string; reasoningEffort?: string }) => Promise<void>; selectPermission: (preset: string) => Promise<void>; send: (text: string) => void; cancel: () => void }) { const [text, setText] = useState(''); const input = useRef<HTMLTextAreaElement>(null); useEffect(() => { if (running) { setText(''); input.current?.blur() } }, [running]); const submit = (event: FormEvent) => { event.preventDefault(); const message = text.trim(); if (!message || running) return; setText(''); send(message) }; const permissionValue = configuration.permissionOptions.some((option) => option.id === configuration.defaultPermission) ? configuration.defaultPermission ?? '' : configuration.permissionOptions[0]?.id ?? ''; const modelPickerDisabled = !hasSession || running || !configuration.available; return <form className="composer" onSubmit={submit}><div className="composer-input-row"><textarea ref={input} value={text} onChange={(event) => setText(event.target.value)} placeholder={running ? 'The Agent is working…' : hasSession ? 'Message the local Agent' : 'Select or create a conversation first'} disabled={running} rows={2} onKeyDown={(event) => { if (event.key === 'Enter' && !event.shiftKey) { event.preventDefault(); event.currentTarget.form?.requestSubmit() } }}/>{running ? <button type="button" className="cancel-turn" onClick={cancel}>Stop</button> : <button className="send" disabled={!text.trim() || !hasSession} aria-label="Send message"><Icon name="arrow"/></button>}</div><div className="composer-controls"><ModelPicker configuration={configuration} disabled={modelPickerDisabled} running={running} selectModel={selectModel}/>{configuration.available && configuration.permissionOptions.length ? <label className="composer-permission"><select aria-label="Permission" title="Set default conversation permission" value={permissionValue} disabled={running} onChange={(event) => void selectPermission(event.target.value)}>{configuration.permissionOptions.map((option) => <option key={option.id} value={option.id}>{option.label}</option>)}</select></label> : configuration.available ? <span className="composer-permission-empty">Permission presets unavailable</span> : <span className="composer-permission-empty">Agent not connected</span>}</div></form> }
function modelSelectionValue(provider: string, model: string) { return JSON.stringify([provider, model]) }
function parseModelSelection(value: string): { provider: string; model: string } | undefined { try { const parsed: unknown = JSON.parse(value); return Array.isArray(parsed) && typeof parsed[0] === 'string' && typeof parsed[1] === 'string' ? { provider: parsed[0], model: parsed[1] } : undefined } catch { return undefined } }
function ModelPicker({ configuration, disabled, running, selectModel }: { configuration: AgentConfiguration; disabled: boolean; running: boolean; selectModel: (input: { provider: string; model: string; reasoningEffort?: string }) => Promise<void> }) { const groups = configuration.models; const selected = configuration.selectedModel; const provider = groups.find((item) => item.id === selected?.provider) ?? groups.find((item) => item.models.length > 0); const model = provider?.models.find((item) => item.id === selected?.model) ?? provider?.models[0]; if (!configuration.available || !provider || !model) return <span className="composer-model-empty">Model unavailable</span>; const value = modelSelectionValue(provider.id, model.id); const effort = model.efforts.some((item) => item.id === selected?.reasoningEffort) ? selected?.reasoningEffort ?? '' : model.defaultEffort ?? model.efforts[0]?.id ?? ''; const handleModelChange = (event: React.ChangeEvent<HTMLSelectElement>) => { const next = parseModelSelection(event.target.value); if (!next) return; const nextProvider = groups.find((item) => item.id === next.provider); const nextModel = nextProvider?.models.find((item) => item.id === next.model); if (nextProvider && nextModel) void selectModel({ provider: nextProvider.id, model: nextModel.id, ...(nextModel.defaultEffort && { reasoningEffort: nextModel.defaultEffort }) }) }; const handleEffortChange = (event: React.ChangeEvent<HTMLSelectElement>) => { void selectModel({ provider: provider.id, model: model.id, reasoningEffort: event.target.value || undefined }) }; return <><label className="composer-model-picker"><select aria-label="Provider and model" title="Switch provider and model" value={value} disabled={disabled || running} onChange={handleModelChange}>{groups.map((group) => <optgroup key={group.id} label={group.name}>{group.models.map((item) => <option key={item.id} value={modelSelectionValue(group.id, item.id)}>{item.name}</option>)}</optgroup>)}</select></label>{model.efforts.length ? <label className="composer-effort-picker"><select aria-label="Reasoning effort" title="Switch reasoning effort" value={effort} disabled={disabled || running} onChange={handleEffortChange}>{model.efforts.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label> : null}</> }
function EmptyWorkspace({ open }: { open: () => void }) { return <div className="empty-state"><img src="./assets/narwhal-icon.png"/><p className="eyebrow">Your local forge</p><h1>Give your agent a place to work.</h1><p>Open a project folder. Narwhal Forge keeps tasks and deliverables on this Mac, separate from your code.</p><button className="primary" onClick={open}><Icon name="folder-plus"/>Open workspace</button></div> }
function EmptyConversation({ create }: { create: () => void }) { return <div className="empty-state"><img src="./assets/narwhal-icon.png"/><p className="eyebrow">Ready when you are</p><h1>Start a local conversation.</h1><p>Narwhal Forge will create an Agent session for this workspace. Your work context stays in this app.</p><button className="primary" onClick={create}><Icon name="plus"/>New conversation</button></div> }
function AgentLoading({ state, retry }: { state: AgentSnapshot['state']; retry: () => void }) { return <div className="empty-state loading"><div className="pulse-orb"/><p className="eyebrow">Local agent</p><h1>{state === 'needs-restart' ? 'The agent needs a restart.' : 'Preparing your local agent.'}</h1><p>{state === 'needs-restart' ? 'Your workspace is safe. Restart the local agent to continue.' : 'Starting the tools, skills, and session runtime on this Mac.'}</p>{state === 'needs-restart' && <button className="primary" onClick={retry}>Restart agent</button>}</div> }
function TaskSection({ task, onSelect, onNew, onUpdate, onTodo, onAddTodo }: { task?: Task; onSelect: (id: string) => void; onNew: () => void; onUpdate: (input: { taskId: string; title?: string; goal?: string; status?: 'active' | 'done' }) => void; onTodo: (taskId: string, todoId: string, done: boolean) => void; onAddTodo: (taskId: string, text: string) => void }) { const [editing, setEditing] = useState(false); const [step, setStep] = useState(''); const complete = task?.todos.filter((item) => item.done).length ?? 0; const total = task?.todos.length ?? 0; useEffect(() => setEditing(false), [task?.id]); if (!task) return <section className="panel-section"><div className="section-title"><span>Plan</span><button onClick={onNew}><Icon name="plus"/></button></div><button className="quiet-add" onClick={onNew}>Create the first task</button></section>; return <section className="panel-section"><div className="section-title"><span>Plan</span><span><button title="Edit task" onClick={() => setEditing(!editing)}><Icon name="settings"/></button><button onClick={onNew}><Icon name="plus"/></button></span></div>{editing ? <div className="task-edit"><input defaultValue={task.title} aria-label="Task title" onBlur={(event) => event.target.value.trim() && onUpdate({ taskId: task.id, title: event.target.value })}/><textarea defaultValue={task.goal} aria-label="Task goal" onBlur={(event) => event.target.value.trim() && onUpdate({ taskId: task.id, goal: event.target.value })}/><label><input type="checkbox" checked={task.status === 'done'} onChange={(event) => onUpdate({ taskId: task.id, status: event.target.checked ? 'done' : 'active' })}/>Mark task complete</label></div> : <button className="task-choice" onClick={() => onSelect(task.id)}>{task.goal}</button>}<div className="progress"><span style={{ width: `${total ? complete / total * 100 : 0}%` }}/></div><small>{complete}/{total} steps complete</small><div className="todos">{task.todos.length ? task.todos.map((todo) => <label key={todo.id}><input type="checkbox" checked={todo.done} onChange={(event) => onTodo(task.id, todo.id, event.target.checked)}/><span>{todo.text}</span></label>) : <p className="muted">No steps yet.</p>}<form className="add-step" onSubmit={(event) => { event.preventDefault(); if (step.trim()) { onAddTodo(task.id, step); setStep('') } }}><input value={step} onChange={(event) => setStep(event.target.value)} placeholder="Add a step"/><button aria-label="Add step"><Icon name="plus"/></button></form></div></section> }
function ChangesSection({ changes }: { changes: readonly { path: string; kind: string }[] }) { return <section className="panel-section"><div className="section-title"><span>Changed files</span><small>{changes.length}</small></div>{changes.length ? <div className="file-list">{changes.slice(0, 7).map((change) => <div key={`${change.kind}-${change.path}`}><code>{change.kind}</code><span title={change.path}>{change.path}</span></div>)}</div> : <p className="muted">No local changes detected.</p>}</section> }
function DeliverablesSection({ entries, onNew, onReveal, onRemove }: { entries: WorkbenchSnapshot['deliverables']; onNew: () => void; onReveal: (path: string) => void; onRemove: (path: string) => void }) { return <section className="panel-section"><div className="section-title"><span>Deliverables</span><button onClick={onNew}><Icon name="plus"/></button></div>{entries.length ? <div className="deliverable-list">{entries.map((item) => <div key={item.relativePath}><button onClick={() => onReveal(item.relativePath)}><Icon name="file"/><span>{item.label}</span><small>{item.relativePath}</small></button><button className="remove" onClick={() => onRemove(item.relativePath)}><Icon name="close"/></button></div>)}</div> : <button className="quiet-add" onClick={onNew}>Pin an output file</button>}</section> }
function TaskDialog({ close, save }: { close: () => void; save: (title: string, goal: string) => Promise<void> }) { const [title, setTitle] = useState(''); const [goal, setGoal] = useState(''); return <Dialog title="New task" close={close}><label>Task title<input autoFocus value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Refine the macOS release"/></label><label>Goal<textarea value={goal} onChange={(event) => setGoal(event.target.value)} placeholder="What does success look like?"/></label><button className="primary" disabled={!title.trim() || !goal.trim()} onClick={() => void save(title, goal)}>Create task</button></Dialog> }
function DeliverableDialog({ close, save }: { close: () => void; save: (path: string, label: string) => Promise<void> }) { const [path, setPath] = useState(''); const [label, setLabel] = useState(''); return <Dialog title="Pin deliverable" close={close}><label>Relative file path<input autoFocus value={path} onChange={(event) => setPath(event.target.value)} placeholder="release/Narwhal Forge.dmg"/></label><label>Label<input value={label} onChange={(event) => setLabel(event.target.value)} placeholder="macOS build"/></label><button className="primary" disabled={!path.trim() || !label.trim()} onClick={() => void save(path, label)}>Pin file</button></Dialog> }
function Dialog({ title, children, close }: { title: string; children: ReactNode; close: () => void }) { return <div className="modal" role="dialog" aria-modal="true"><form className="dialog" onSubmit={(event) => event.preventDefault()}><div><h2>{title}</h2><button className="close-dialog" onClick={close}><Icon name="close"/></button></div>{children}</form></div> }
function SettingsDialog({ settings, agent, close, restart }: { settings: DesktopSettings; agent: AgentSnapshot; close: () => void; restart: () => void }) {
  const [tab, setTab] = useState<'models' | 'providers' | 'permissions' | 'runtime'>('models')
  const [configuration, setConfiguration] = useState<AgentConfiguration>({ available: false, writable: false, providers: [], models: [], permissionOptions: [], customProvider: { available: false, protocols: [] } })
  const [message, setMessage] = useState('')
  const load = async () => { try { setMessage(''); setConfiguration(await api.getAgentConfiguration()) } catch { setMessage('Unable to load local Agent settings.') } }
  useEffect(() => { void load() }, [])
  const update = async (operation: () => Promise<AgentConfiguration>, notice = 'Saved locally.') => { try { setMessage(''); setConfiguration(await operation()); if (notice) setMessage(notice) } catch { setMessage('The local Agent rejected that setting. Nothing was changed.') } }
  const createProvider = async (input: { id: string; displayName?: string; baseUrl: string; protocol: string; modelId: string; apiKey?: string }) => { try { setMessage(''); const result = await api.createProvider(input); setConfiguration(result.configuration); setMessage(result.keyStored ? 'Provider created locally.' : 'Provider was created, but the API key was rejected. Add the key from its provider row.'); return true } catch (error) { setMessage(error instanceof Error ? error.message : 'The local Agent rejected this provider. Nothing was created.'); return false } }
  const navigation: ReadonlyArray<{ readonly id: typeof tab; readonly label: string; readonly icon: string }> = [{ id: 'models', label: 'Models', icon: 'model' }, { id: 'providers', label: 'Providers', icon: 'provider' }, { id: 'permissions', label: 'Permissions', icon: 'shield' }, { id: 'runtime', label: 'Runtime', icon: 'runtime' }]
  const selectTab = (next: typeof tab) => { setTab(next); document.getElementById(`settings-tab-${next}`)?.focus() }
  const onTabKeyDown = (event: ReactKeyboardEvent<HTMLButtonElement>) => { const index = navigation.findIndex((item) => item.id === tab); const key = event.key; const nextIndex = key === 'ArrowDown' || key === 'ArrowRight' ? (index + 1) % navigation.length : key === 'ArrowUp' || key === 'ArrowLeft' ? (index - 1 + navigation.length) % navigation.length : key === 'Home' ? 0 : key === 'End' ? navigation.length - 1 : undefined; if (nextIndex === undefined) return; event.preventDefault(); selectTab(navigation[nextIndex].id) }
  return <div className="modal" role="dialog" aria-modal="true" aria-label="Settings"><section className="dialog settings-dialog"><header className="settings-head"><div><p>Local workbench</p><h2>Settings</h2></div><button className="close-dialog" aria-label="Close settings" onClick={close}><Icon name="close"/></button></header><div className="settings-body"><nav className="settings-nav" aria-label="Settings sections" role="tablist" aria-orientation="vertical">{navigation.map((item) => <button id={`settings-tab-${item.id}`} key={item.id} role="tab" aria-selected={tab === item.id} aria-controls={`settings-panel-${item.id}`} tabIndex={tab === item.id ? 0 : -1} className={tab === item.id ? 'active' : ''} onClick={() => setTab(item.id)} onKeyDown={onTabKeyDown}><Icon name={item.icon}/><span>{item.label}</span></button>)}</nav><div id={`settings-panel-${tab}`} className="settings-content" role="tabpanel" aria-labelledby={`settings-tab-${tab}`} tabIndex={0}>{message && <p className="settings-notice" role="status">{message}</p>}{!configuration.available && tab !== 'runtime' ? <p className="settings-empty">{configuration.error ?? 'This local Agent does not expose its settings plane.'}</p> : tab === 'models' ? <ModelSettings configuration={configuration} update={update}/> : tab === 'providers' ? <ProviderSettings configuration={configuration} update={update} create={createProvider} openModels={() => selectTab('models')}/> : tab === 'permissions' ? <PermissionSettings configuration={configuration} update={update}/> : <RuntimeSettings settings={settings} agent={agent} restart={restart}/>}</div></div></section></div>
}
function ModelSettings({ configuration, update }: { configuration: AgentConfiguration; update: (operation: () => Promise<AgentConfiguration>, notice?: string) => void }) { const current = configuration.selectedModel; const provider = configuration.models.find((item) => item.id === current?.provider) ?? configuration.models[0]; const model = provider?.models.find((item) => item.id === current?.model) ?? provider?.models[0]; const currentMatches = current?.provider === provider?.id && current?.model === model?.id; const effort = currentMatches ? current?.reasoningEffort ?? model?.defaultEffort ?? '' : model?.defaultEffort ?? ''; const select = (nextProvider: AgentConfiguration['models'][number], nextModel: AgentConfiguration['models'][number]['models'][number], nextEffort?: string) => update(() => api.selectAgentModel({ provider: nextProvider.id, model: nextModel.id, ...(nextEffort && { reasoningEffort: nextEffort }) }), ''); return <section className="settings-page model-settings"><div className="active-model-heading"><p>Active model</p><small>This choice applies to the current conversation and becomes the default for new conversations.</small></div>{provider && model ? <div className="model-controls"><label>Provider<select value={provider.id} onChange={(event) => { const nextProvider = configuration.models.find((item) => item.id === event.target.value); const nextModel = nextProvider?.models[0]; if (nextProvider && nextModel) select(nextProvider, nextModel, nextModel.defaultEffort) }}>{configuration.models.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Model<select value={model.id} onChange={(event) => { const nextModel = provider.models.find((item) => item.id === event.target.value); if (nextModel) select(provider, nextModel, nextModel.defaultEffort) }}>{provider.models.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>{model.efforts.length ? <label>Reasoning effort<select value={effort} onChange={(event) => select(provider, model, event.target.value || undefined)}>{model.efforts.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label> : null}</div> : <p className="settings-empty">No models are currently available from the local Host.</p>}</section> }
function ProviderSettings({ configuration, update, create, openModels }: { configuration: AgentConfiguration; update: (operation: () => Promise<AgentConfiguration>) => void; create: (input: { id: string; displayName?: string; baseUrl: string; protocol: string; modelId: string; apiKey?: string }) => Promise<boolean>; openModels: () => void }) { const [adding, setAdding] = useState(false); const capability = configuration.customProvider; return <section className="settings-page providers-page"><div className="settings-page-intro"><p>Credentials remain write-only. Add a compatible route from the local Host schema.</p>{!adding && <button type="button" className="add-provider" title={capability.available ? 'Add provider' : capability.reason} disabled={!capability.available} onClick={() => setAdding(true)}><Icon name="plus"/>Add provider</button>}</div>{adding && <CreateProviderForm protocols={capability.protocols} close={() => setAdding(false)} submit={async (input) => { const created = await create(input); if (created) setAdding(false); return created }}/>} {configuration.providers.length ? <div className="provider-list">{configuration.providers.map((provider) => <ProviderRow key={provider.id} provider={provider} update={update} models={configuration.models.find((group) => group.id === provider.id)?.models ?? []} openModels={openModels}/>)}</div> : <p className="settings-empty">No configurable providers are available from the local Agent.</p>}{!capability.available && <p className="provider-hint"><Icon name="info"/>{capability.reason ?? 'Custom providers are not available from this local Host.'}</p>}</section> }
function CreateProviderForm({ protocols, close, submit }: { protocols: readonly string[]; close: () => void; submit: (input: { id: string; displayName?: string; baseUrl: string; protocol: string; modelId: string; apiKey?: string }) => Promise<boolean> }) { const [id, setId] = useState(''); const [displayName, setDisplayName] = useState(''); const [baseUrl, setBaseUrl] = useState(''); const [protocol, setProtocol] = useState(protocols[0] ?? ''); const [modelId, setModelId] = useState(''); const [apiKey, setApiKey] = useState(''); const [saving, setSaving] = useState(false); const ready = id.trim() && baseUrl.trim() && protocol && modelId.trim(); return <form className="provider-create" onSubmit={(event) => { event.preventDefault(); if (!ready || saving) return; setSaving(true); void submit({ id: id.trim(), ...(displayName.trim() && { displayName: displayName.trim() }), baseUrl: baseUrl.trim(), protocol, modelId: modelId.trim(), ...(apiKey.trim() && { apiKey: apiKey.trim() }) }).then((created) => { if (created) setApiKey(''); setSaving(false) }) }}><header className="provider-create-title"><div><strong>New custom provider</strong><small>Profile and model are created together. API key is optional.</small></div><button type="button" className="close-provider-create" aria-label="Close provider form" title="Close provider form" onClick={close}><Icon name="close"/></button></header><div className="provider-fields"><label>Provider ID<input value={id} onChange={(event) => setId(event.target.value)} placeholder="my-provider" autoCapitalize="none" autoCorrect="off"/></label><label>Display name (optional)<input value={displayName} onChange={(event) => setDisplayName(event.target.value)} placeholder="My Provider"/></label><label className="provider-wide">Base URL<input value={baseUrl} onChange={(event) => setBaseUrl(event.target.value)} placeholder="https://api.example.com/v1" inputMode="url"/></label><label>API protocol<select value={protocol} onChange={(event) => setProtocol(event.target.value)}>{protocols.map((option) => <option key={option} value={option}>{option}</option>)}</select></label><label>Model ID<input value={modelId} onChange={(event) => setModelId(event.target.value)} placeholder="model-name" autoCapitalize="none" autoCorrect="off"/></label><label className="provider-wide">API key (optional)<input type="password" autoComplete="off" value={apiKey} onChange={(event) => setApiKey(event.target.value)} placeholder="Stored write-only after the profile is created"/></label></div><div className="provider-create-actions"><span>Provider ID cannot be changed after creation.</span><button type="submit" className="primary" disabled={!ready || saving}>{saving ? 'Creating…' : 'Create provider'}</button></div></form> }
function ProviderRow({ provider, update, models, openModels }: { provider: AgentConfiguration['providers'][number]; update: (operation: () => Promise<AgentConfiguration>) => void; models: readonly AgentConfiguration['models'][number]['models'][number][]; openModels: () => void }) { const [baseUrl, setBaseUrl] = useState(provider.baseUrl ?? ''); const [key, setKey] = useState(''); useEffect(() => setBaseUrl(provider.baseUrl ?? ''), [provider.baseUrl]); const capabilities = [provider.active ? 'Available' : 'Inactive', provider.apiKeyWritable ? 'Key managed' : 'No key editor', provider.baseUrl !== undefined ? 'Custom endpoint' : null].filter(Boolean); return <article className="provider-row"><header><div><strong>{provider.name}</strong><small>{capabilities.join(' · ')}</small></div><span className={provider.apiKeyConfigured ? 'credential ready' : 'credential'}>{provider.apiKeyConfigured ? 'Configured' : 'Needs key'}</span></header><div className="provider-model-action">{models.length ? <><span>{models.length === 1 ? `${models[0].name} available` : `${models.length} models available`}</span><button type="button" onClick={openModels}>Select model</button></> : <span>No models available from this provider.</span>}</div>{provider.baseUrl !== undefined && <label>Base URL<div className="field-action"><input value={baseUrl} onChange={(event) => setBaseUrl(event.target.value)} placeholder="https://api.example.com"/><button type="button" onClick={() => update(() => api.setProviderBaseUrl({ provider: provider.id, value: baseUrl }))} disabled={!baseUrl.trim()}>Save</button></div></label>}{provider.apiKeyWritable && <label>API key<div className="field-action"><input type="password" autoComplete="off" value={key} onChange={(event) => setKey(event.target.value)} placeholder={provider.apiKeyConfigured ? 'Replace stored key' : 'Paste API key'}/><button type="button" onClick={() => { update(() => api.setProviderApiKey({ provider: provider.id, value: key })); setKey('') }} disabled={!key.trim()}>Save</button></div></label>}</article> }
function PermissionSettings({ configuration, update }: { configuration: AgentConfiguration; update: (operation: () => Promise<AgentConfiguration>) => void }) { return <section className="settings-page"><p>This default is used by new conversations. It does not alter the current conversation.</p>{configuration.permissionOptions.length ? <label>New conversation permission<select value={configuration.defaultPermission ?? ''} onChange={(event) => { const next = event.target.value; if (next.toLowerCase().includes('full') && !window.confirm('Full access can allow unrestricted local tool operations. Continue?')) return; update(() => api.setDefaultPermission(next)) }}>{configuration.permissionOptions.map((option) => <option key={option.id} value={option.id}>{option.label}</option>)}</select></label> : <p className="settings-empty">Permission presets are unavailable from this Host.</p>}</section> }
function RuntimeSettings({ settings, agent, restart }: { settings: DesktopSettings; agent: AgentSnapshot; restart: () => void }) { return <section className="settings-page"><div className="settings-status"><span className={`status-dot ${agent.state}`}/><div><strong>{statusText(agent.state)}</strong><small>Local Agent runtime</small></div></div><dl className="settings-list"><div><dt>App version</dt><dd>{settings.appVersion}</dd></div><div><dt>Runtime</dt><dd>{settings.runtimeVersion}</dd></div><div><dt>Workbench data</dt><dd title={settings.dataDirectory}>{settings.dataDirectory}</dd></div></dl><button className="primary" type="button" onClick={restart} disabled={agent.state === 'starting'}>{agent.state === 'starting' ? 'Starting Agent…' : 'Restart Agent'}</button></section> }
createRoot(document.getElementById('root')!).render(<StrictMode><App/></StrictMode>)
